language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
  - npm install
script:
- npm run lint
- npm test
- npm run build
 notifications:
    slack: blackturtleneck:K7yY5QCF1cKhXglMypLXJEYP